name: Flutter CI (FVM)

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true   # 🔥 important
        # ✅ FIRST Flutter install (this provides Dart)
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.6'   # তোমার version

      - name: Install FVM
        run: dart pub global activate fvm

      - name: Set PATH
        run: echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

      - name: Install Flutter
        run: fvm install

      - name: Pub get
        run: fvm flutter pub get

      - name: Analyze
        run: fvm flutter analyze --no-fatal-warnings

      - name: Test
        run: fvm flutter test || true

      - name: Build APK
        run: fvm flutter build apk --release